### ISSUE TITLE
tensorflow.python.framework.errors_imple.InvalidArgumentError.

### ISSUE THREAD

**Issue by huiMM** [xuanjihe/speech-emotion-recognition#15]
Then I run the code in my enviroment, An Issue occured and I tried to find the solution.
The error Info is ：
Traceback (most recent call last):
  File "D:/******/3D-speech-emotion-recognition-master/model-cnn.py", line 372, in <module>
    train_op(1)
  File "D:/*******/3D-speech-emotion-recognition-master/model-cnn.py", line 358, in train_op
    loss, train_acc = sess.run([cost,accuracy],feed_dict = {X:valid_data, Y:valid_label,is_training:False, keep_prob:1})
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must be same size: logits_size=[654,6] labels_size=[436,6]
	 [[Node: SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape_5, Reshape_6)]]

Caused by op 'SoftmaxCrossEntropyWithLogits', defined at:
  File "D:/2_exp-emotion/3D-emotion/3D-speech-emotion-recognition-master/model.py", line 372, in <module>
    train_op(1)
  File "D:/2_exp-emotion/3D-emotion/3D-speech-emotion-recognition-master/model.py", line 303, in train_op
    cross_entropy = tf.nn.softmax_cross_entropy_with_logits(labels =  Y, logits =  Ylogits)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1597, in softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 2385, in _softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): logits and labels must be same size: logits_size=[654,6] labels_size=[436,6]
	 [[Node: SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape_5, Reshape_6)]]

**Comment by dyf102** [comment]
How was this issue solved?
