### ISSUE TITLE
IndexError: index 4833 is out of bounds for size 4800

### ISSUE THREAD

**Issue by vinay-wwtc** [xuanjihe/speech-emotion-recognition#41]
Getting below index error on model.py.

np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "model.py", line 139, in <module>
    train()
  File "model.py", line 56, in train
    train_label = dense_to_one_hot(train_label,FLAGS.num_classes)
  File "model.py", line 49, in dense_to_one_hot
    labels_one_hot.flat[index_offset + labels_dense.ravel()] = 1
IndexError: index 4833 is out of bounds for size 4800

Dependency
- Python 3.7.8
- pip 20.1.1
- tensorflow 2.2
- win 10 64bit

**Comment by Garthchatrikalpana-github** [comment]
How to rectify this error,please tell me
